# Generated by Django 6.0.2 on 2026-02-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daysoff",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="duty",
            name="date",
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="daysoff",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="unique_day_off"
            ),
        ),
    ]
