# Generated by Django 6.0.2 on 2026-02-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_alter_daysoff_date_alter_duty_date_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="dutyassignment",
            constraint=models.UniqueConstraint(
                fields=("user", "duty"), name="unique_user_duty"
            ),
        ),
    ]
