# Generated by Django 6.0.2 on 2026-02-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_dutyassignment_unique_user_duty"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="staff",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__gte", 0)), name="priority_gte_0"
            ),
        ),
    ]
