# Generated by Django 6.0.2 on 2026-05-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0004_staff_priority_gte_0"),
    ]

    operations = [
        migrations.AddField(
            model_name="dutyassignment",
            name="jira_issue_key",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
