# Generated by Django 6.0.2 on 2026-05-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0005_dutyassignment_jira_issue_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="jira_team_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
