# Generated by Django 6.0.2 on 2026-05-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0006_staff_jira_team_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="jira_account_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
