# Generated by Django 6.0.2 on 2026-05-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0007_staff_jira_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="dutyassignment",
            name="is_synced",
            field=models.BooleanField(default=False),
        ),
    ]
