# Generated by Django 6.0.2 on 2026-05-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0008_dutyassignment_is_synced"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dutyassignment",
            name="jira_issue_key",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="staff",
            name="jira_account_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="staff",
            name="jira_team_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
